// Table layout and inline styles work in Gmail, Apple Mail and Outlook.
const GOLD = '#FDDD56';
const BASE_URL = 'https://itc-backend-1031252664334.us-east1.run.app';
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const languageOf = value => ['es', 'en', 'pt'].includes(value) ? value : 'es';
function baseUrl() { return (process.env.PUBLIC_BASE_URL || BASE_URL).replace(/\/$/, ''); }
function actionUrl(target, language) { return `${baseUrl()}/app/${target}?lang=${languageOf(language)}`; }
function dateLabel(value, language) {
  if (!value || !Number.isFinite(new Date(value).getTime())) return null;
  return new Date(value).toLocaleDateString({ es: 'es-US', en: 'en-US', pt: 'pt-BR' }[languageOf(language)], { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'America/New_York' });
}
const COPY = {
  es: { welcome: 'Bienvenido a ITC CLUB', canceled: 'Membresía cancelada', resumed: 'Renovación reactivada', hello: 'Hola', active: 'Tu membresía está activa. Descubre beneficios y experiencias para disfrutar Nueva York.', price: 'Precio', next: 'Próxima renovación', until: 'Conservas tus beneficios hasta', cancel: 'La renovación automática de tu membresía ha sido cancelada.', noCharge: 'No se realizarán nuevos cobros de renovación. Tu cuenta seguirá disponible.', reactivate: 'Puedes reactivar la renovación desde Perfil > Mi membresía antes de que termine tu período.', benefits: 'Ver mis beneficios', membership: 'Ver mi membresía', notice: 'Tu membresía se renueva automáticamente al precio indicado hasta que la canceles. Cómo cancelar: abre Perfil > Mi membresía para administrar o cancelar la renovación. Conservas el acceso hasta el final del período pagado.', restored: 'La renovación automática está activa nuevamente, al precio de tu plan actual. Puedes cancelarla desde Perfil > Mi membresía.', terms: 'Términos', privacy: 'Privacidad', support: 'Soporte', unknown: 'Consulta los detalles en Mi membresía', periods: { month: 'mes', year: 'año', week: 'semana', day: 'día' } },
  en: { welcome: 'Welcome to ITC CLUB', canceled: 'Membership canceled', resumed: 'Renewal reactivated', hello: 'Hi', active: 'Your membership is active. Discover benefits and experiences to enjoy New York.', price: 'Price', next: 'Next renewal', until: 'Your benefits remain available until', cancel: 'Your automatic membership renewal has been canceled.', noCharge: 'No further renewal payments will be taken. Your account remains available.', reactivate: 'You can reactivate renewal in Profile > My membership before your period ends.', benefits: 'View my benefits', membership: 'View my membership', notice: 'Your membership renews automatically at the stated price until you cancel. Manage or cancel renewal in Profile > My membership. You keep access until the end of the paid period.', restored: 'Automatic renewal is active again at your current plan price. You can cancel it in Profile > My membership.', terms: 'Terms', privacy: 'Privacy', support: 'Support', unknown: 'View the details in My membership', periods: { month: 'month', year: 'year', week: 'week', day: 'day' } },
  pt: { welcome: 'Bem-vindo ao ITC CLUB', canceled: 'Assinatura cancelada', resumed: 'Renovação reativada', hello: 'Olá', active: 'Sua assinatura está ativa. Descubra benefícios e experiências para aproveitar Nova York.', price: 'Preço', next: 'Próxima renovação', until: 'Seus benefícios continuam até', cancel: 'A renovação automática da sua assinatura foi cancelada.', noCharge: 'Não haverá novas cobranças de renovação. Sua conta continua disponível.', reactivate: 'Você pode reativar a renovação em Perfil > Minha assinatura antes do fim do período.', benefits: 'Ver meus benefícios', membership: 'Ver minha assinatura', notice: 'Sua assinatura é renovada automaticamente pelo preço indicado até você cancelar. Gerencie ou cancele em Perfil > Minha assinatura. Você mantém o acesso até o fim do período pago.', restored: 'A renovação automática está ativa novamente pelo preço do plano atual. Você pode cancelar em Perfil > Minha assinatura.', terms: 'Termos', privacy: 'Privacidade', support: 'Suporte', unknown: 'Veja os detalhes em Minha assinatura', periods: { month: 'mês', year: 'ano', week: 'semana', day: 'dia' } },
};
function membershipEmail(user, kind = 'welcome', language = user.language) {
  const lang = languageOf(language); const c = COPY[lang];
  const welcome = kind === 'welcome'; const canceled = kind === 'cancel';
  const title = welcome ? c.welcome : canceled ? c.canceled : c.resumed;
  const greeting = `${c.hello}${user.name ? `, ${user.name}` : ''}`;
  const date = dateLabel(user.subscription_current_period_end, lang) || c.unknown;
  const price = user.subscription_amount_cents == null ? c.unknown : `${new Intl.NumberFormat({ es: 'es-US', en: 'en-US', pt: 'pt-BR' }[lang], { style: 'currency', currency: (user.subscription_currency || 'usd').toUpperCase() }).format(user.subscription_amount_cents / 100)} / ${c.periods[user.subscription_interval] || user.subscription_interval || c.periods.month}`;
  const body = welcome ? c.active : canceled ? c.cancel : c.restored;
  const detailLabel = canceled ? c.until : c.next;
  const note = welcome ? c.notice : canceled ? `${c.noCharge} ${c.reactivate}` : c.notice;
  const target = welcome ? 'benefits' : 'membership'; const button = welcome ? c.benefits : c.membership;
  const url = actionUrl(target, lang);
  const legal = slug => `${baseUrl()}/legal/${slug}?lang=${lang}`;
  const row = (label, value) => `<tr><td style="padding:14px 12px;border-bottom:1px solid #333;color:#ccc">${escape(label)}</td><td style="padding:14px 12px;border-bottom:1px solid #333;color:#fff">${escape(value)}</td></tr>`;
  const html = `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${escape(title)}</title></head><body style="margin:0;padding:24px 10px;background:#080808;color:#fff;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">${escape(body)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#0A0A0A;border:1px solid #303030"><tr><td align="center" style="padding:30px 20px;font-size:38px;line-height:46px;font-weight:800;letter-spacing:-1px;white-space:nowrap;color:#fff">ITC <span style="color:${GOLD}">CLUB</span></td></tr>${welcome ? `<tr><td><img src="${baseUrl()}/email-assets/new-york.jpg" alt="New York" width="600" style="display:block;width:100%;height:auto;border:0"></td></tr>` : `<tr><td align="center" style="padding:16px;color:${GOLD};font-size:46px" aria-hidden="true">${canceled ? '⊗' : '✓'}</td></tr>`}<tr><td style="padding:28px 24px"><h1 style="font-size:28px;line-height:1.25;margin:0 0 20px;text-align:center;color:#fff">${welcome ? `${escape(title.replace(' CLUB', ''))} <span style="color:${GOLD}">CLUB</span>` : escape(title)}</h1><div style="height:3px;width:50px;background:${GOLD};margin:0 auto 28px"></div><p style="font-size:18px;font-weight:700;color:#fff">${escape(greeting)},</p><p style="font-size:16px;line-height:1.6;color:#ddd">${escape(body)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#151515;border:1px solid #333;border-radius:12px;font-size:15px;margin:22px 0">${!canceled ? row(c.price, price) : ''}${row(detailLabel, date)}</table><table role="presentation" cellspacing="0" cellpadding="0" align="center" style="margin:24px auto"><tr><td bgcolor="${GOLD}" style="background:${GOLD};border-radius:10px;text-align:center"><a href="${escape(url)}" style="display:inline-block;padding:17px 30px;color:#0A0A0A;font-size:17px;font-weight:800;text-decoration:none;border:1px solid ${GOLD};border-radius:10px">${escape(button)}</a></td></tr></table><p style="font-size:14px;line-height:1.6;color:#ccc">${escape(note)}</p><hr style="border:0;border-top:1px solid #333;margin:28px 0 20px"><p style="text-align:center;color:#aaa;font-size:13px;line-height:1.8;margin:0">ITC CLUB · Insight The City<br><a style="color:#ccc" href="${legal('subscription')}">${escape(c.terms)}</a> · <a style="color:#ccc" href="${legal('privacy')}">${escape(c.privacy)}</a> · <a style="color:#ccc" href="mailto:noreply@insightthecity.com">${escape(c.support)}</a></p></td></tr></table></td></tr></table></body></html>`;
  return { subject: welcome ? { es: 'Tu membresía está activa · ITC CLUB', en: 'Your membership is active · ITC CLUB', pt: 'Sua assinatura está ativa · ITC CLUB' }[lang] : `${title} · ITC CLUB`, html, text: [title, '', greeting, body, !canceled ? `${c.price}: ${price}` : '', `${detailLabel}: ${date}`, '', note, '', `${button}: ${url}`, `${c.terms}: ${legal('subscription')}`, `${c.privacy}: ${legal('privacy')}`, `${c.support}: noreply@insightthecity.com`, 'ITC CLUB · Insight The City'].filter(Boolean).join('\n') };
}
module.exports = { membershipEmail, actionUrl, escape, languageOf, COPY, GOLD };
